version: "3.9"
services:
  server:
    build:  ./flask-server
    ports: 
    - "5000:5000"
    volumes: 
    - ./flask-server:/code
    environment: 
      FLASK_ENV: development
  web:
    build: ./client/my-app
    ports: 
      - "3000:3000"
    volumes: 
      - ./client/my-app:/usr/src/app
    depends_on: 
      - server
